import assert from "node:assert/strict";
import { schedule, policy } from "./lib/review-policy.mjs";
assert.deepEqual(policy.clean_days, [7, 7, 21]);
const event = (date, result, id = date, session = date) => ({ date, result, id, session });
let state = schedule({}, event("2026-09-01", "pass"));
assert.equal(state.due, "2026-09-08");
assert.equal(state.cleanStreak, 1);
assert.deepEqual(schedule(state, event("2026-09-01", "pass")), state, "interrupted replay must not double count");
state = schedule(state, event("2026-09-01", "pass", "retry", "2026-09-01"));
assert.equal(state.cleanStreak, 1, "same-session retry is not independent recall");
state = schedule(state, event("2026-09-08", "pass"));
assert.equal(state.due, "2026-09-15");
state = schedule(state, event("2026-09-15", "pass"));
assert.equal(state.due, "2026-10-06");
assert.equal(state.retired, false);
state = schedule(state, event("2026-10-06", "pass"));
assert.equal(state.due, "2026-10-27");
assert.equal(state.retired, false);
state = schedule(state, event("2026-11-05", "pass"));
assert.equal(state.retired, true);
assert.equal(state.due, null);
state = schedule(state, event("2026-11-06", "fail"));
assert.equal(state.retired, false);
assert.equal(state.cleanStreak, 0);
assert.equal(state.due, "2026-11-07");
state = schedule(state, event("2026-11-07", "fail"));
assert.equal(state.activeWeakness, true);
state = schedule(state, event("2026-11-08", "partial"));
assert.equal(state.due, "2026-11-11");
assert.equal(state.cleanStreak, 0);
assert.equal(schedule({}, event("2024-02-28", "partial")).due, "2024-03-02");
assert.equal(state.activeWeakness, true, "partial recall cannot erase an established weakness");
assert.equal(schedule({}, event("2026-12-31", "fail")).due, "2027-01-01");
assert.equal(schedule({ attempts: 20 }, event("2026-09-01", "pass")).cleanStreak, 1, "legacy attempt count is not a success streak");
assert.throws(() => schedule({}, event("2026-02-30", "pass")), /invalid date/);
assert.throws(() => schedule(state, event("2025-01-01", "pass")), /precede/);
console.log("Review policy date vectors passed: streaks, same-session retry, replay, retirement/reactivation, failures, partial recall and calendar boundaries. This does not prove model compliance.");
